[package]
name = "todos-postgres"
version = "0.1.0"
edition = "2018"
workspace = "../../"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.4.0", features = [ "attributes" ] }
futures = "0.3"
paw = "1.0"
sqlx = { version = "0.2", features = ["postgres"] }
structopt = { version = "0.3", features = ["paw"] }
