[package]
name = "sqlx-example-postgres-listen"
version = "0.1.0"
edition = "2021"
workspace = "../../../"

[dependencies]
sqlx = { path = "../../../", features = [ "postgres", "tls", "runtime-tokio-native-tls" ] }
futures = "0.3.1"
tokio = { version = "1.20.0", features = ["macros"]}
tui = "0.19.0"
crossterm = "0.25"
unicode-width = "0.1"
