[package]
name = "sqlx-macros"
version = "0.2.4"
repository = "https://github.com/launchbadge/sqlx"
description = "Macros for SQLx, the rust SQL toolkit. Not intended to be used directly."
license = "MIT OR Apache-2.0"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[lib]
proc-macro = true

[features]
default = [ "runtime-async-std" ]

runtime-async-std = [ "sqlx/runtime-async-std", "async-std" ]
runtime-tokio = [ "sqlx/runtime-tokio", "tokio", "lazy_static" ]

# database
mysql = [ "sqlx/mysql" ]
postgres = [ "sqlx/postgres" ]

# type
chrono = [ "sqlx/chrono" ]
uuid = [ "sqlx/uuid" ]

[dependencies]
async-std = { version = "1.5.0", default-features = false, optional = true }
tokio = { version = "0.2.13", default-features = false, features = [ "rt-threaded" ], optional = true }
dotenv = { version = "0.15.0", default-features = false }
futures = { version = "0.3.4", default-features = false, features = [ "executor" ] }
proc-macro2 = { version = "1.0.9", default-features = false }
sqlx = { version = "0.2.5", default-features = false, path = "../sqlx-core", package = "sqlx-core" }
syn = { version = "1.0.16", default-features = false, features = [ "full" ] }
quote = { version = "1.0.2", default-features = false }
url = { version = "2.1.1", default-features = false }
lazy_static = { version = "1.4.0", optional = true }
